parameters:
    file_manager:
        directory: '%kernel.project_dir%/public/data/'
    mailer:
        templateFolder: mails/
        sender:
            name: TasteHub App
            email: noreply@tastehub.app
    pictogram:
        basePath: build/images/pictogram
    reset_password:
        token_lifetime: 2 # In hours

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

